# Default values for cover-service-faktor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

ingress:
  enabled: true
  enableAuth: false
  enableTLS: false

app:
  image:
    version: latest
    pullPolicy: IfNotPresent
  elastic_url: "http://elasticsearch-es-http:9200/"
  redis:
    server: "redis"
    port: "6379"
    cache_db: "12"
  php:
    max_children: "20"
    start_servers: "2"
    min_spare_servers: "2"
    max_spare_servers: "3"
  mongodb:
    server: "faktor-mongo-mongodb.cover-service.svc.cluster.local"
    port: "27017"
    database: "faktor"
    storage:
      size: "30Gi"
      class: "managed-premium-retain"

nginx:
  exporter:
    image:
      version: 0.6.0